load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_macro_library", "scala_binary", "scala_test", "scala_repl")

scala_binary(
    name = "HelloWorld",
    main_class = "com.week1.WeekOne",
    srcs = [
        "WeekOne.scala",
    ]
)